extends:
  - remcohaszing
  - remcohaszing/jest
env:
  jest/globals: true
settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: tsconfig.json

rules:
  camelcase: 'off'
  '@typescript-eslint/naming-convention': 'off'

overrides:
  - files:
      - '*.md/*.js'
    rules:
      import/extensions: 'off'
