extends:
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
plugins:
  - simple-import-sort
parserOptions:
  project: tsconfig.json
rules:
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off
  'simple-import-sort/sort': error
overrides:
  - files:
      - '*.ts'
