name: Node CI

on:
  - push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: ESLint
        run: |
          yarn --frozen-lockfile
          yarn eslint .

  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8, 10, 12]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          yarn --frozen-lockfile
          yarn test

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Prettier
        run: |
          yarn --frozen-lockfile
          yarn prettier

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: TSC
        run: |
          yarn --frozen-lockfile
          yarn tsc
