name: NodeJS

on:
  - pull_request
  - push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: ESLint
        run: |
          yarn --frozen-lockfile
          yarn eslint .

  jest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          yarn --frozen-lockfile
          yarn test --coverage
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.node-version == 16 }}

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Prettier
        run: |
          yarn --frozen-lockfile
          yarn prettier --check .

  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: TSC
        run: |
          yarn --frozen-lockfile
          yarn tsc
